language: php

php:
  - 5.4
  - 5.5
  - 5.6

before_script:
  - composer update
 
script:
  - cd test
  - phpunit --coverage-clover ../build/logs/clover.xml

after_script:
  - php ../vendor/bin/coveralls -v
